import { describe, expect, it } from 'vitest'

import { resolveStoryPromotionDecision } from './promotion'

describe('resolveStoryPromotionDecision', () => {
  it('stages as experimental when gates fail', () => {
    const decision = resolveStoryPromotionDecision({ gatesPassed: false, reviewed: true })

    expect(decision.ok).toBe(true)
    if (!decision.ok) {
      return
    }

    expect(decision.value.packClass).toBe('experimental')
    expect(decision.value.promoted).toBe(false)
  })

  it('stages as experimental when review is missing', () => {
    const decision = resolveStoryPromotionDecision({ gatesPassed: true, reviewed: false })

    expect(decision.ok).toBe(true)
    if (!decision.ok) {
      return
    }

    expect(decision.value.packClass).toBe('experimental')
    expect(decision.value.promoted).toBe(false)
  })

  it('promotes to generated by default after review', () => {
    const decision = resolveStoryPromotionDecision({ gatesPassed: true, reviewed: true })

    expect(decision.ok).toBe(true)
    if (!decision.ok) {
      return
    }

    expect(decision.value.packClass).toBe('generated')
    expect(decision.value.promoted).toBe(true)
  })

  it('supports explicit reviewed promotion class', () => {
    const decision = resolveStoryPromotionDecision({
      gatesPassed: true,
      reviewed: true,
      requestedClass: 'curated',
    })

    expect(decision.ok).toBe(true)
    if (!decision.ok) {
      return
    }

    expect(decision.value.packClass).toBe('curated')
  })
})
